application: bokerface-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

# env_variables:
#   DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /static/
  static_dir: static

- url: /3sylDTpaSwmN7OOfiht2aJHytxM.html
  static_files: static/3sylDTpaSwmN7OOfiht2aJHytxM.html
  upload: static/3sylDTpaSwmN7OOfiht2aJHytxM.html

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml

- url: /google47f813d05fe65499.html
  static_files: static/google47f813d05fe65499.html
  upload: static/google47f813d05fe65499.html

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: 1.3

builtins:
- deferred: on